Correct changeid error message

diff --git a/binaries/anonsurf b/binaries/anonsurf
--- a/binaries/anonsurf
+++ b/binaries/anonsurf
@@ -172,7 +172,7 @@ function change {
 	# Change Tor node automatically
 	# Use Tor control port
 	if [ "$(systemctl is-active anonsurfd)" = "inactive" ]; then
-		echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running! Can't stop service!$RESETCOLOR\n" >&2
+		echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running! Can't get new ID!$RESETCOLOR\n" >&2
 	else
 		if [ -f /etc/anonsurf/nyxrc ]; then
 			passwd=`cat /etc/anonsurf/nyxrc | cut -d " " -f 2`
