Temp remove service

diff --git a/binaries/anonsurf b/binaries/anonsurf
--- a/binaries/anonsurf
+++ b/binaries/anonsurf
@@ -97,16 +97,16 @@ function start {
 }
 
 
-function start-bridge {
-	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Starting anonymous mode via obfs4 bridge:$RESETCOLOR\n"
+# function start-bridge {
+# 	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Starting anonymous mode via obfs4 bridge:$RESETCOLOR\n"
 
-	/usr/sbin/service anonsurfd start bridge
+# 	/usr/sbin/service anonsurfd start bridge
 
-	echo -e "$GREEN *$BLUE All traffic was redirected throught Tor\n"
-	echo -e "$GREEN[$BLUE i$GREEN ]$BLUE You are under AnonSurf tunnel$RESETCOLOR\n"
-	notify "Global Anonymous Proxy Activated"
-	sleep 1
-}
+# 	echo -e "$GREEN *$BLUE All traffic was redirected throught Tor\n"
+# 	echo -e "$GREEN[$BLUE i$GREEN ]$BLUE You are under AnonSurf tunnel$RESETCOLOR\n"
+# 	notify "Global Anonymous Proxy Activated"
+# 	sleep 1
+# }
 
 
 function stop {
@@ -170,24 +170,23 @@ case "$1" in
 		checkuid
 		if [ "$(systemctl is-active anonsurfd)" = "inactive" ]; then
 			zenity --question --text="Do you want anonsurf to kill dangerous applications and clean some application caches?" --width 400 && kill-apps
-			echo -e "$GREEN *$BLUE Generating Torrc"
 			start
 		else
 			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is running! Can't start service!$RESETCOLOR\n" >&2
 		fi
 	;;
-	start-bridge)
-	# Only start if anonsurfd is not running
-	# TODO try to run if the service status is failed?
-		checkuid
-		if [ "$(systemctl is-active anonsurfd)" = "inactive" ]; then
-			zenity --question --text="Do you want anonsurf to kill dangerous applications and clean some application caches?" --width 400 && kill-apps
-			echo -e "$GREEN *$BLUE Generating Torrc with Obfs4 bridge"
-			start-bridge
-		else
-			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is running! Can't start service!$RESETCOLOR\n" >&2
-		fi
-	;;
+
+	# start-bridge)
+	# # Only start if anonsurfd is not running
+	# # TODO try to run if the service status is failed?
+	# 	checkuid
+	# 	if [ "$(systemctl is-active anonsurfd)" = "inactive" ]; then
+	# 		zenity --question --text="Do you want anonsurf to kill dangerous applications and clean some application caches?" --width 400 && kill-apps
+	# 		start-bridge
+	# 	else
+	# 		echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is running! Can't start service!$RESETCOLOR\n" >&2
+	# 	fi
+	# ;;
 	
 	stop)
 	# Only stop if the anonsurfd is running
